services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: portal-app:latest          # ← beri nama image hasil build
    container_name: laravel_app
    volumes:
      - .:/var/www
      - vendor:/var/www/vendor
      - storage:/var/www/storage
    networks:
      - laravel
    depends_on:
      db:
        condition: service_healthy
    environment:
      - APP_ENV=local
      - APP_DEBUG=false
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=portalmahasiswa
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - QUEUE_CONNECTION=database

  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: always
    environment:
      MYSQL_DATABASE: portalmahasiswa
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - laravel
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
    command: --performance_schema=ON --innodb_buffer_pool_size=256M

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel_phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - laravel

  queue:
    image: portal-app:latest           # ← gunakan image yang sama
    container_name: laravel_queue
    working_dir: /var/www
    volumes:
      - .:/var/www
      - vendor:/var/www/vendor
      - storage:/var/www/storage
    networks:
      - laravel
    depends_on:
      - app
      - db
    command: php artisan queue:work --sleep=3 --tries=3 --max-time=3600
    restart: unless-stopped

  scheduler:
    image: portal-app:latest           # ← gunakan image yang sama
    container_name: laravel_scheduler
    working_dir: /var/www
    volumes:
      - .:/var/www
      - vendor:/var/www/vendor
      - storage:/var/www/storage
    networks:
      - laravel
    depends_on:
      - app
      - db
    command: php artisan schedule:work
    restart: unless-stopped

volumes:
  vendor:
  storage:

networks:
  laravel: